#!/bin/sh

if [ $# -eq 0 ]
  then
    PROJ=$(basename $(pwd))
  else
    PROJ=$1
fi


dotnet new sln
dotnet new mgdesktopgl -o $PROJ
dotnet sln add $PROJ/$PROJ.csproj

mkdir $PROJ.Tests
cd $PROJ.Tests
dotnet new nunit
dotnet add reference ../$PROJ/$PROJ.csproj
cd ..
dotnet sln add $PROJ.Tests/$PROJ.Tests.csproj

echo "Inspired by this reddit post:"
echo "https://www.reddit.com/r/monogame/comments/cst49i/the_ultimate_guide_to_getting_started_with/"
