from node:14-alpine3.12

RUN apk update \
 && apk add -u --no-cache \
            bash \
            curl \
            git \
            jq \
            less \
            openssh-client \
            vim \
