name: Test Pull Request
on:
  pull_request:

jobs:
  get_matrix:
    name: Get workflow matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      repo: ${{ steps.set-repo.outputs.repo }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.0.2
      - id: set-matrix
        run: echo "::set-output name=matrix::{'include':[$(./.github/scripts/get_pr_matrix.sh | paste -sd ',' -)]}"
      - id: set-repo
        run: echo "::set-output name=repo::$(echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')"

  build_test:
    needs: get_matrix
    name: Build "${{ matrix.image }}" and test
    if: matrix.include
    env:
      image_name: "${{ needs.get_matrix.outputs.repo }}/${{ matrix.image }}"
      image_path: "images/${{ matrix.image }}"
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.get_matrix.outputs.matrix) }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.3.4

      - name: Test images
        run: ./.github/scripts/test_images.sh ${{ env.image_path }} ${{ env.image_name }}
